"""
HITL (Human-in-the-Loop) Proposal Engine

This module implements a persistent approval workflow where high-stakes AI actions
must be approved by a human operator before execution. Proposals are stored in
PostgreSQL instead of volatile memory, ensuring they survive system restarts.

The workflow:
1. Agent creates a proposal -> stored in hitl_proposals table (status='pending')
2. Proposal is sent to Mattermost for human review
3. Human replies with 'Approve <task_id>' or 'Reject <task_id>'
4. System updates proposal status in database and executes/cancels action
"""
from typing import Dict, Any, Optional, Callable, List
from pydantic import BaseModel, Field
import uuid
from datetime import datetime
import threading
import time
import re
import json
import traceback
from loguru import logger
from typing import TYPE_CHECKING

from cobalt_agent.config import get_config

if TYPE_CHECKING:
    from cobalt_agent.interfaces.mattermost import MattermostInterface


class HITLProposalStore:
    """
    Persistent storage for HITL (Human-in-the-Loop) proposals using Postgres.
    Stores proposals in the hitl_proposals table instead of volatile memory.
    """
    
    def __init__(self):
        from cobalt_agent.memory.postgres import PostgresMemory
        self.postgres = PostgresMemory()
    
    def create_proposal(self, task_id: str, tool_name: str, tool_kwargs: Dict[str, Any]) -> None:
        """
        Create a new pending proposal and store it in the database.
        
        Args:
            task_id: The 8-character task ID (generated by caller)
            tool_name: Name of the tool to be executed
            tool_kwargs: JSON-serializable arguments for the tool
        """
        try:
            # Force explicit JSON serialization
            args_json = json.dumps(tool_kwargs)
            current_time = datetime.now()
            
            # Get connection from postgres memory
            conn = self.postgres._get_conn()
            
            # Explicitly open a cursor and execute
            with conn.cursor() as cur:
                print(f"[DEBUG] Attempting to insert proposal {task_id} into hitl_proposals")
                cur.execute(
                    """
                    INSERT INTO hitl_proposals (id, status, tool_name, tool_kwargs, created_at, updated_at)
                    VALUES (%s, %s, %s, %s, %s, %s)
                    """,
                    (task_id, 'pending', tool_name, args_json, current_time, current_time)
                )
            # Force a hard commit regardless of autocommit settings
            conn.commit()
            print(f"[DEBUG] Successfully committed proposal {task_id} to database.")
            conn.close()
            logger.info(f"HITL proposal created: [{task_id}] for tool '{tool_name}'")
            
        except Exception as e:
            print(f"[CRITICAL ERROR] Failed to insert proposal: {str(e)}")
            print(traceback.format_exc())
            # Rollback just in case
            try:
                conn.rollback()
            except Exception:
                pass
            raise
    
    def get_proposal(self, proposal_id: str) -> Optional[Dict[str, Any]]:
        """
        Retrieve a proposal by ID.
        
        Args:
            proposal_id: The UUID of the proposal
            
        Returns:
            Dictionary with proposal data, or None if not found
        """
        try:
            conn = self.postgres._get_conn()
            try:
                result = conn.execute("""
                    SELECT id, status, tool_name, tool_kwargs, created_at, updated_at
                    FROM hitl_proposals
                    WHERE id = %s
                """, (proposal_id,)).fetchone()
                
                if result:
                    return {
                        "id": str(result[0]),
                        "status": result[1],
                        "tool_name": result[2],
                        "tool_kwargs": result[3] if isinstance(result[3], dict) else json.loads(result[3]),
                        "created_at": result[4],
                        "updated_at": result[5]
                    }
                return None
            finally:
                conn.close()
        except Exception as e:
            logger.error(f"Failed to get proposal: {e}")
            return None
    
    def get_pending_proposals(self) -> List[Dict[str, Any]]:
        """
        Get all pending proposals.
        
        Returns:
            List of dictionaries with pending proposal data
        """
        try:
            conn = self.postgres._get_conn()
            try:
                results = conn.execute("""
                    SELECT id, status, tool_name, tool_kwargs, created_at, updated_at
                    FROM hitl_proposals
                    WHERE status = %s
                """, ('pending',)).fetchall()
                
                proposals = []
                for row in results:
                    proposals.append({
                        "id": str(row[0]),
                        "status": row[1],
                        "tool_name": row[2],
                        "tool_kwargs": row[3] if isinstance(row[3], dict) else json.loads(row[3]),
                        "created_at": row[4],
                        "updated_at": row[5]
                    })
                return proposals
            finally:
                conn.close()
        except Exception as e:
            logger.error(f"Failed to get pending proposals: {e}")
            return []
    
    def update_status(self, proposal_id: str, status: str) -> bool:
        """
        Update the status of a proposal.
        
        Args:
            proposal_id: The UUID of the proposal
            status: The new status ('approved', 'rejected', 'pending')
            
        Returns:
            True if successful, False otherwise
        """
        try:
            conn = self.postgres._get_conn()
            try:
                with conn.cursor() as cur:
                    print(f"[DEBUG] Attempting to update proposal {proposal_id} status to '{status}'")
                    cur.execute("""
                        UPDATE hitl_proposals
                        SET status = %s,
                            updated_at = CURRENT_TIMESTAMP
                        WHERE id = %s
                    """, (status, proposal_id))
                # Force a hard commit regardless of autocommit settings
                conn.commit()
                print(f"[DEBUG] Successfully committed status update for proposal {proposal_id}")
                logger.info(f"HITL proposal [{proposal_id}] status updated to '{status}'")
                return True
            finally:
                conn.close()
        except Exception as e:
            print(f"[CRITICAL ERROR] Failed to update proposal status: {str(e)}")
            print(traceback.format_exc())
            try:
                conn.rollback()
            except Exception:
                pass
            logger.error(f"Failed to update proposal status: {e}")
            return False
    
    def delete_proposal(self, proposal_id: str) -> bool:
        """
        Delete a proposal from the database.
        
        Args:
            proposal_id: The UUID of the proposal
            
        Returns:
            True if successful, False otherwise
        """
        try:
            conn = self.postgres._get_conn()
            try:
                conn.execute("""
                    DELETE FROM hitl_proposals WHERE id = %s
                """, (proposal_id,))
                # With autocommit=True, no manual commit needed
                logger.info(f"HITL proposal [{proposal_id}] deleted")
                return True
            finally:
                conn.close()
        except Exception as e:
            logger.error(f"Failed to delete proposal: {e}")
            return False


# --- PROPOSAL MODEL ---
class Proposal(BaseModel):
    """Standardized ticket for high-stakes AI actions."""
    task_id: str = Field(default_factory=lambda: str(uuid.uuid4())[:8])
    action: str = Field(description="The specific command or operation to be executed.")
    justification: str = Field(description="The agent's reasoning for why this action is necessary.")
    risk_assessment: str = Field(description="A summary of potential negative impacts (e.g., data loss, capital risk).")
    parameters: Dict[str, Any] = Field(default_factory=dict, description="Technical metadata required for execution.")
    timestamp: datetime = Field(default_factory=datetime.now)
    approved: bool = False
    approval_channel: Optional[str] = None
    approval_message_id: Optional[str] = None

    def format_for_mattermost(self) -> str:
        return (
            f"### 🛡️ ACTION PROPOSAL [{self.task_id}]\n"
            f"**Action:** `{self.action}`\n\n"
            f"**Justification:** {self.justification}\n"
            f"**Risk:** {self.risk_assessment}\n\n"
            f"### ⚠️ ACTION REQUIRED: Reply exactly with 'Approve {self.task_id}' to execute."
        )


# --- PROPOSAL ENGINE ---
class ProposalEngine:
    """
    The Proposal Engine enforces the Prime Directive by requiring human approval
    before executing high-stakes actions. It creates proposals, sends them to
    Mattermost for approval, and only executes approved actions.
    
    Proposals are stored in the hitl_proposals Postgres table for persistence.
    """
    
    def __init__(self):
        self.config = get_config()
        self.approval_channel = self.config.mattermost.approval_channel
        self.approval_team = self.config.mattermost.approval_team
        self.mattermost: Optional[Any] = None
        self._hitl_store: Optional[HITLProposalStore] = None
        self._callbacks: Dict[str, Callable[[str, Dict[str, Any]], None]] = {}
        self._approval_callback: Optional[Callable[[str, Dict[str, Any]], None]] = None
        self._monitoring: bool = False
        self._monitor_thread: Optional[threading.Thread] = None
        
        logger.info(f"Proposal Engine initialized (Channel: {self.approval_channel})")
    
    def _get_hitl_store(self) -> HITLProposalStore:
        """Get or create the HITL proposal store."""
        if self._hitl_store is None:
            self._hitl_store = HITLProposalStore()
        return self._hitl_store
    
    def connect_mattermost(self) -> bool:
        """Connect to Mattermost for approval workflow."""
        if self.mattermost:
            return True
        
        from cobalt_agent.interfaces.mattermost import MattermostInterface
        
        self.mattermost = MattermostInterface()
        connected = self.mattermost.connect()
        
        if connected:
            self.mattermost.brain = self._get_brain_for_approval_routing()
            logger.info("Proposal Engine: Mattermost connection established")
        
        return connected
    
    def _get_brain_for_approval_routing(self) -> Any:
        """
        Get the brain instance for approval routing.
        This is a stub - the actual brain should be passed in or connected externally.
        """
        return None
    
    def create_proposal(self, tool_name: str, tool_kwargs: dict) -> str:
        """
        Create a new proposal for a tool action and store it in Postgres.
        
        Args:
            tool_name: Name of the tool to be executed
            tool_kwargs: Dictionary of arguments for the tool
            
        Returns:
            The 8-character task_id of the created proposal
        """
        # Generate the task ID
        task_id = uuid.uuid4().hex[:8]
        
        # Store in Postgres (primary storage for persistence)
        hitl_store = self._get_hitl_store()
        hitl_store.create_proposal(task_id, tool_name, tool_kwargs)
        
        logger.info(f"Proposal created and stored: [{task_id}] {tool_name}")
        return task_id
    
    def send_proposal(self, proposal: Proposal) -> bool:
        """
        Send a proposal to Mattermost for approval.
        
        Args:
            proposal: The Proposal object to send
            
        Returns:
            True if proposal was sent successfully
        """
        if not self.mattermost:
            logger.error("Mattermost not connected. Cannot send proposal.")
            return False
        
        if not self.approval_channel:
            logger.error("Approval channel not configured.")
            return False
        
        message = proposal.format_for_mattermost()
        
        try:
            teams = self.mattermost.driver.teams.get_team_by_name(self.approval_team)
            if not teams:
                logger.error(f"Approval team not found: {self.approval_team}")
                return False
            
            team_id = teams["id"]
            
            channel = self.mattermost.driver.channels.get_channel_by_name(team_id, self.approval_channel)
            if not channel:
                logger.error(f"Approval channel not found: {self.approval_channel} in team {self.approval_team}")
                return False
            
            channel_id = channel["id"]
            
            post = self.mattermost.driver.posts.create_post(
                options={
                    "channel_id": channel_id,
                    "message": message
                }
            )
            
            if post and "id" in post:
                proposal.approval_message_id = post["id"]
                proposal.approval_channel = channel_id
                logger.info(f"Proposal sent to Mattermost: [{proposal.task_id}]")
                return True
            else:
                logger.error("Failed to send proposal to Mattermost")
                return False
                
        except Exception as e:
            logger.error(f"Failed to send proposal: {e}")
            return False
    
    def approve_and_get_payload(self, task_id: str) -> Optional[Dict[str, Any]]:
        """
        Approve a proposal and return the tool execution payload.
        
        This method implements the "Airlock" pattern:
        1. Updates the proposal status to 'approved' in the database
        2. Commits the transaction immediately
        3. Returns the tool_name and tool_kwargs without executing the tool
        
        The interface layer (e.g., Mattermost) is responsible for executing the tool
        after the DB transaction is closed, preventing deadlocks.
        
        Args:
            task_id: The 8-character ID of the proposal to approve
            
        Returns:
            Dictionary with 'tool_name' and 'tool_kwargs' keys, or None if not found
            Example: {"tool_name": "browser", "tool_kwargs": {"query": "test"}}
        """
        try:
            # First, get the proposal data from the database
            db_proposal = self._get_hitl_store().get_proposal(task_id)
            
            if not db_proposal:
                logger.warning(f"Approval for unknown task_id: {task_id}")
                return None
            
            if db_proposal.get("status") != "pending":
                # Already processed (approved or rejected)
                status = db_proposal.get("status", "unknown")
                if status == "approved":
                    logger.info(f"Proposal [{task_id}] was already approved.")
                elif status == "rejected":
                    logger.info(f"Proposal [{task_id}] was already rejected.")
                return None
            
            # Update status to approved (this commits the transaction immediately)
            self._get_hitl_store().update_status(task_id, 'approved')
            
            # Return the tool execution payload (NOT executing the tool here!)
            tool_kwargs = db_proposal.get("tool_kwargs", {})
            if isinstance(tool_kwargs, str):
                tool_kwargs = json.loads(tool_kwargs)
                
            payload = {
                "tool_name": db_proposal.get("tool_name"),
                "tool_kwargs": tool_kwargs
            }
            
            logger.info(f"Proposal approved and payload returned for [{task_id}]: tool='{payload.get('tool_name')}'")
            return payload
            
        except Exception as e:
            logger.error(f"Failed to approve and get payload for [{task_id}]: {e}")
            return None
    
    def handle_approval_response(self, message: str, channel_id: Optional[str] = None) -> Optional[str]:
        """
        Check if a message is an approval response for a pending proposal and return a formatted message.
        
        Args:
            message: The message text from Mattermost
            channel_id: Optional channel ID where the message was posted
            
        Returns:
            A formatted message string if this is a valid approval response, None otherwise
        """
        # Check if this is an approval message
        approval_pattern = r"approve\s+(\w{8})"
        match = re.search(approval_pattern, message.lower())
        
        if not match:
            # Check for reject pattern
            reject_pattern = r"reject\s+(\w{8})"
            reject_match = re.search(reject_pattern, message.lower())
            if reject_match:
                task_id = reject_match.group(1)
                # Check database for this task_id
                hitl_store = self._get_hitl_store()
                db_proposal = hitl_store.get_proposal(task_id)
                if db_proposal:
                    # Proposal exists - check if it's still pending
                    if db_proposal.get("status") == "pending":
                        # Mark as rejected
                        hitl_store.update_status(task_id, 'rejected')
                    # Proposal already processed (approved or rejected), return rejection message
                    return f"🛑 Action [{task_id}] was rejected by the administrator. Execution aborted."
                # Proposal doesn't exist at all
                return f"🛑 Action [{task_id}] was rejected by the administrator. Execution aborted."
            return None
        
        task_id = match.group(1)
        
        # Validate channel if provided
        if channel_id and self.approval_channel and channel_id != self.approval_channel:
            return None
        
        # Get the payload without executing the tool
        payload = self.approve_and_get_payload(task_id)
        
        if payload:
            logger.info(f"Approval processed for [{task_id}], tool execution delegated to interface layer")
            # Return message indicating approval was processed - tool execution happens in interface layer
            return f"✅ Approval received for task [{task_id}]. Tool '{payload.get('tool_name')}' queued for execution."
        else:
            logger.warning(f"Approval for unknown task_id: {task_id}")
            return f"⚠️ No pending approval found for task [{task_id}]."
    
    def wait_for_approval(self, task_id: str, timeout: int = 3600) -> bool:
        """
        Wait for a proposal to be approved by polling the database.
        
        Args:
            task_id: The 8-character ID of the proposal to wait for
            timeout: Maximum time to wait in seconds (default 1 hour)
            
        Returns:
            True if approved, False if timed out
        """
        start_time = time.time()
        
        while True:
            hitl_store = self._get_hitl_store()
            db_proposal = hitl_store.get_proposal(task_id)
            
            if db_proposal is None:
                logger.warning(f"Proposal [{task_id}] not found while waiting for approval")
                return False
            
            if db_proposal.get("status") == "approved":
                logger.info(f"Proposal [{task_id}] has been approved")
                return True
            
            if db_proposal.get("status") == "rejected":
                logger.info(f"Proposal [{task_id}] has been rejected")
                return False
            
            # Check timeout
            if time.time() - start_time >= timeout:
                logger.warning(f"Approval timeout for proposal: [{task_id}]")
                return False
            
            # Wait before polling again
            time.sleep(0.5)
    
    def execute_approved(self, proposal: Proposal, tool_manager: Any = None) -> bool:
        """
        Execute an approved proposal's action.
        
        Args:
            proposal: The approved Proposal to execute
            tool_manager: Optional ToolManager instance to execute the tool
            
        Returns:
            True if execution succeeded
        """
        if not proposal.approved:
            logger.error(f"Cannot execute unapproved proposal: [{proposal.task_id}]")
            return False
        
        task_id = proposal.task_id
        
        try:
            action = proposal.action
            logger.info(f"Executing approved action: {action}")
            
            # Extract tool name and kwargs from the action string
            # Action format is typically "Tool: tool_name" with kwargs in parameters
            if tool_manager and action.startswith("Tool: "):
                tool_name = action[6:].strip()  # Remove "Tool: " prefix
                tool_kwargs = proposal.parameters or {}
                
                # Execute with bypass_hitl=True (VIP pass)
                result = tool_manager.execute_tool(tool_name, tool_kwargs, bypass_hitl=True)
                logger.info(f"VIP tool execution result: {result}")
            
            if self._approval_callback:
                self._approval_callback(task_id, {"tool_name": tool_name, "tool_kwargs": tool_kwargs})
            
            return True
        except Exception as e:
            logger.error(f"Failed to execute approved action [{proposal.task_id}]: {e}")
            return False
    
    def set_approval_callback(self, task_id: str, callback: Callable[[str, Dict[str, Any]], None]) -> None:
        """
        Set a callback function to be called when a proposal is approved.
        
        Args:
            task_id: The unique identifier for the task
            callback: Function that takes (task_id, payload) and returns None
                      where payload is {"tool_name": str, "tool_kwargs": dict}
        """
        self._callbacks[task_id] = callback
        logger.info(f"Approval callback set for task [{task_id}]")
    
    def start_monitoring(self) -> None:
        """Start monitoring for approval responses in the background."""
        if self._monitoring:
            logger.warning("Monitoring already running")
            return
        
        self._monitoring = True
        self._monitor_thread = threading.Thread(target=self._monitor_approval_channel, daemon=True)
        self._monitor_thread.start()
        logger.info("Proposal Engine monitoring started")
    
    def _monitor_approval_channel(self) -> None:
        """Background thread to monitor the approval channel for approval responses."""
        logger.info("Approval channel monitoring started (WebSocket listener attached to MattermostInterface)")
    
    def stop_monitoring(self) -> None:
        """Stop monitoring for approval responses."""
        self._monitoring = False
        if self._monitor_thread:
            self._monitor_thread.join(timeout=1)
        logger.info("Proposal Engine monitoring stopped")


# --- CONVENIENCE FUNCTION ---
def create_proposal_and_send_to_mattermost(
    tool_name: str,
    tool_kwargs: dict
) -> Optional[str]:
    """
    Convenience function to create a proposal and send it to Mattermost.
    
    Args:
        tool_name: Name of the tool to be executed
        tool_kwargs: Dictionary of arguments for the tool
        
    Returns:
        The task_id if successful, None otherwise
    """
    engine = ProposalEngine()
    
    if not engine.connect_mattermost():
        logger.error("Failed to connect to Mattermost")
        return None
    
    task_id = engine.create_proposal(tool_name, tool_kwargs)
    
    # Note: The send_proposal method expects a Proposal object which no longer
    # exists in the new flow. The tool execution happens after approval.
    # This function creates the proposal and returns the task_id for display.
    
    logger.info(f"Proposal created: [{task_id}] {tool_name}")
    return task_id
